on:
  workflow_dispatch: #manual
  push:
    paths-ignore:
      - .github/**
    branches:
      - main
jobs:
  trigger-workflows:
    uses: eitan-brightleaf/.github/.github/workflows/pcp-wp-deploy.yml@main
    secrets:
      WP_SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
      WP_SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
